---
driver:
  name: docker
  privileged: true
  use_sudo: false
  forward:
    - 8787

provisioner:
  name: ansible_playbook
  roles_path: roles
  hosts: rstudio-servers
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  require_chef_for_busser: false

platforms:
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y

verifier:
  ruby_bindir: '/usr/bin'

suites:
  - name: default
