---
# built against ubuntu 14.04 LTS
# assumes apt
- name: get build depts
  apt: name={{ item }} update_cache=yes
  with_items:
    - automake
    - autotools-dev
    - g++
    - git
    - libcurl4-gnutls-dev
    - libfuse-dev
    - libssl-dev
    - libxml2-dev
    - make
    - pkg-config
- name: glone repo
  git:
    repo: https://github.com/s3fs-fuse/s3fs-fuse.git
    dest: "{{ s3fs_repo }}"
- name: run s3fs automake
  shell:
    chdir: "{{ s3fs_repo }}"
    cmd: ./autogen.sh
    creates: "{{ s3fs_repo }}/configure"
- name: run s3fs configure
  shell:
    chdir: "{{ s3fs_repo }}"
    cmd: ./configure
    creates: "{{ s3fs_repo }}/Makefile"
- name: Compile s3fs    
  shell:
    chdir: "{{ s3fs_repo }}"
    cmd: make
    creates: "{{ s3fs_repo }}/src/s3fs"
- name: install s3fs
  shell:
    chdir: "{{ s3fs_repo }}"
    cmd: make install
    creates: /usr/local/bin/s3fs

## use when moving to ansible 2
#- name: Compile s3fs    
#  make:
#    chdir: "{{ s3fs_repo }}"
#- name: Install s3fs    
#  make:
#    chdir: "{{ s3fs_repo }}"
#    target: install
