---
- name: Add Cran repo
#  sudo: true
  apt_repository: repo='deb https://mirrors.nics.utk.edu/cran/bin/linux/ubuntu trusty/' state=present
- name: add repo key
  apt_key: keyserver=keyserver.ubuntu.com id=E084DAB9 
- name: Install r base
  apt: name=r-base update_cache=yes
